export const projects = [
  {
    id: 1,
    title: "Solsea",
    tags: ["React", "Scss", "Bootstrap"],
    image: "/projects/solsea.png",
  },
  {
    id: 2,
    title: "Solsea Dashboard",
    tags: ["React", "UI/UX", "Bootstrap"],
    image: "/project1.png",
  },
  {
    id: 3,
    title: "All.Art API",
    tags: ["Node", "MongoDB"],
    image: "/projects/api-default.png",
  },
  {
    id: 4,
    title: "Shapa App",
    tags: ["React Native", "Firebase", "SCSS"],
    image: "/project3.png",
  },
  {
    id: 5,
    title: "Shapa Website",
    tags: ["React", "UI/UX"],
    image: "/projects/shapa-web-logo.png",
  },
  {
    id: 6,
    title: "Shapa API",
    tags: ["Nest", "Firebase", "PostgreSQL"],
    image: "/projects/api-default.png",
  },
  {
    id: 7,
    title: "Shapa Dashboard",
    tags: ["React"],
    image: "/project3.png",
  },
  {
    id: 8,
    title: "Palace of Science: Create an Avatar",
    tags: ["React", "Electron", "SCSS"],
    image: "/projects/vise-od-igre-2.webp",
  },
  {
    id: 9,
    title: "Palace of Science: Create Your Own Game",
    tags: ["React", "Electron", "SCSS"],
    image: "/projects/vise-od-igre-2.webp",
  },
  {
    id: 10,
    title: "Panther Wallet",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/project2.png",
  },
  {
    id: 30,
    title: "Panther Wallet API",
    tags: ["Node", "MongoDB"],
    image: "/projects/api-default.png",
  },
  {
    id: 11,
    title: "RWA - Virtus Winery",
    tags: ["Next", "Tailwind", "Material ui"],
    image: "/projects/rwa-virtus.png",
  },
  {
    id: 12,
    title: "3AS - Website",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/projects/3as-web.png",
  },
  {
    id: 13,
    title: "3AS - Agents",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/projects/3as-agents.png",
  },
  {
    id: 14,
    title: "3AS - Tools",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/projects/3as-tools.png",
  },
  {
    id: 15,
    title: "3AS - Tools Bundle",
    tags: ["Node", "MongoDB"],
    image: "/projects/api-default.png",
  },
  {
    id: 16,
    title: "3AS - Chat",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/project2.png",
  },
  {
    id: 17,
    title: "3AS - Forge",
    tags: ["Next", "Tailwind", "Shadcn"],
    image: "/projects/3as-forge.png",
  },
  {
    id: 18,
    title: "3AS - Extension",
    tags: ["Next", "Scss"],
    image: "/projects/extension-default.png",
  },
];
